### ISSUE TITLE
Previous and Next buttons for sites

### ISSUE THREAD

**Issue by olendorf** [olendorf/grenada_archaeology#1]

**Comment by hannaj5** [comment]
This is so you can go between detailed entries of each site without having to go back to the main table and click "view" again. I've just been changing the entry in the address bar, but buttons would be better.

**Comment by olendorf** [comment]
@hannaj5 I believe this is done. Using active admin limits how we can arrange the page so its not quite as elegant as I like but it works pretty well. Over time things can be tweaked.

**Comment by hannaj5** [comment]
Ok, yeah, that's good-enough for now!
