### ISSUE TITLE
Default Dashboard page

### ISSUE THREAD

**Issue by olendorf** [olendorf/grenada_archaeology#2]

**Comment by hannaj5** [comment]
I just was just thinking of adding something to the default "Dashboard" page. In hindsight, this page seem unnecessary-- would be better to go straight to the main "archaeological sites" table

**Comment by olendorf** [comment]
You could also have a nice pretty home page and other pages for help etc. These would be outside active admin and be more pure HTML.

**Comment by hannaj5** [comment]
Yeah, that's true. I have a site set up on GrenadaArchaeology.com, with a portal ready for this, so I could put help pages on there, as needed. 

How can I make it skip the Dashboard (or automatically redirect to Archaeological Sites after hitting the Dashboard)?

**Comment by olendorf** [comment]
I did this. It might be easier to get your work on the site folded into this. Would take some work but doable. its also possible to operated them as two sites.  is this running on wordpress?

**Comment by hannaj5** [comment]
Oh, that was easier than I thought, thanks.

GrenadaArchaeology is just my own html/csv file hosted directly on GoogleDomains. We can keep these as two separate sites, at least in the beginning-- unless you think it would be easier to fold everything into one?

**Comment by olendorf** [comment]
I think the goal would be to make it into one. But keeping them separate will work in the meantime. Just put a link on your site to the Archeological Sites URL, once we go live. Also we can get rid of the front page on the Rails site for the time being, although that is hwere your google sites material would go.

**Comment by hannaj5** [comment]
ok, sounds good
