### ISSUE TITLE
Thumbnail of image/map for each site

### ISSUE THREAD

**Issue by olendorf** [olendorf/grenada_archaeology#3]
@hannaj5 not sure exactly what you want here. could you describe it more?

**Comment by hannaj5** [comment]
This is for decorating the main table "Archeological Sites" a bit by adding a small thumbnail image (from "map" field) next to it. Maybe that's easily done by showing the "map" column? I was thinking of taking off some of these other columns from the main page anyway.

**Comment by olendorf** [comment]
@hannaj5  Yeap, it won't be hard, just need to know what to show.

**Comment by hannaj5** [comment]
I'd like it to show a small thumbnail of the image in "map" (That field is better described as "main image" than "map" since it's often not a map at all)

I reduced what is displayed on the main index page (didn't need everything), but I couldn't get the thumbnail to display.

**Comment by hannaj5** [comment]
I also moved the "map" image to the top of the detail page

**Comment by olendorf** [comment]
@hannaj5  Ok, i have it in the develop branch. You can merge it to using `git pull origin develop` while you are on the develop branch in cloud 9. It works like this.

1) If there are no maps or images it shows a no image image.
2) If there are one or more images, it shows the first one by default.
3) you can choose other ones in the edit form using a drop down menu.

If you want to change the term from map to images or something that is easy to do. just let me know.

**Comment by hannaj5** [comment]
This looks great, thanks!
