### ISSUE TITLE
Change display entries to include line breaks.

### ISSUE THREAD

**Issue by olendorf** [olendorf/grenada_archaeology#4]
I think this is a "feature" of html. It ignores multiple line breaks and spaces assuming they are one in text. There are ways around it though.

**Comment by hannaj5** [comment]
Ok, that's true-- I've noticed that on other websites before. It's essential for this, though, because some of those entries are really long.

**Comment by olendorf** [comment]
I'll look into how best to do this.

**Comment by olendorf** [comment]
The line breaks are still in the data. Just not being displayed, so this should be pretty easy to fix.

**Comment by olendorf** [comment]
OK even easier than I thought. Just use the simple_format helper.

example. 
```
#  app/admin/archeological_sites.rb 

# lines 73 - 85
...
  show title: :site_name, span: 6 do
    panel 'Description' do
      content_tag :p, simple_format(resource.location_description)
    end
    panel 'Summary' do
      content_tag :p, simple_format(resource.summary)
    end
    panel 'Recommendations' do
      content_tag :p, simple_format(resource.recommendations)
    end
    panel 'References' do
      content_tag :p, simple_format(resource.references)
    end
...

**Comment by hannaj5** [comment]
Awesome, that looks great!
